import csv, json

# Read patrol sheet
with open('patrol_sheet.csv', mode='r', encoding='utf-8', errors='ignore') as f:
    rows = list(csv.reader(f))

staff_records = []

# 1. PERMANENT STAFF (5 records with Employee ID)
perm_staff = [
    {
        "id": "EMP-101518",
        "employeeId": "EMP-101518",
        "awpoId": None,
        "name": "Shri Vivek Kumar Azad",
        "nameHi": "श्री विवेक कुमार आज़ाद",
        "fatherName": "Shri R. P. Azad",
        "post": "Assistant Project Manager / Civil",
        "designation": "APM",
        "role": "SUPER_ADMIN",
        "staffCategory": "PERMANENT",
        "dutyType": "OFFICER",
        "employmentType": "REGULAR",
        "email": "vkazad@dfcc.co.in",
        "phone": "8872671873",
        "emergencyContact": "8872671873",
        "headquarters": "IMSD SMUN",
        "assignedSection": "KRJN - CHAN (Full SMUN Unit)",
        "joiningDate": "2020-08-15",
        "pmeDate": "2027-04-15",
        "leaveDate": "2026-10-01",
        "beatNo": "All Section",
        "beatFromTo": "Km 1167.210 to 1249.720",
        "patrolPairId": None,
        "patrolPartnerId": None,
        "patrolPartnerName": None,
        "leaveBalance": {"lap": 30, "lhap": 15, "cl": 8, "rh": 2},
        "qrCodeId": "RD-EMP-101518",
        "remarks": "Overall In-Charge / Assistant Project Manager Civil"
    },
    {
        "id": "EMP-100412",
        "employeeId": "EMP-100412",
        "awpoId": None,
        "name": "Shri Rajesh Sharma",
        "nameHi": "श्री राजेश शर्मा",
        "fatherName": "Shri D. C. Sharma",
        "post": "Joint Project Manager / Civil",
        "designation": "JPM",
        "role": "SUPER_ADMIN",
        "staffCategory": "PERMANENT",
        "dutyType": "OFFICER",
        "employmentType": "REGULAR",
        "email": "rajesh.jpm@dfcc.co.in",
        "phone": "8295416161",
        "emergencyContact": "8295416161",
        "headquarters": "IMSD SMUN",
        "assignedSection": "KRJN - CHAN Section",
        "joiningDate": "2021-02-10",
        "pmeDate": "2026-11-20",
        "leaveDate": "2026-09-15",
        "beatNo": "Civil HQ",
        "beatFromTo": "Km 1167.210 to 1249.720",
        "patrolPairId": None,
        "patrolPartnerId": None,
        "patrolPartnerName": None,
        "leaveBalance": {"lap": 28, "lhap": 15, "cl": 6, "rh": 2},
        "qrCodeId": "RD-EMP-100412",
        "remarks": "Joint Project Manager / Civil"
    },
    {
        "id": "EMP-100523",
        "employeeId": "EMP-100523",
        "awpoId": None,
        "name": "Shri Ved Prakash",
        "nameHi": "श्री वेद प्रकाश",
        "fatherName": "Shri Ram Swaroop",
        "post": "Senior Executive / P-Way",
        "designation": "Sr.Executive",
        "role": "OFFICER",
        "staffCategory": "PERMANENT",
        "dutyType": "OFFICER",
        "employmentType": "REGULAR",
        "email": "vedprakash.sre@dfcc.co.in",
        "phone": "7665685189",
        "emergencyContact": "7665685189",
        "headquarters": "IMSD SMUN",
        "assignedSection": "SMUN - SBJN Block Section",
        "joiningDate": "2021-06-01",
        "pmeDate": "2026-09-10",
        "leaveDate": "2026-08-25",
        "beatNo": "P-Way Section 1",
        "beatFromTo": "Km 1170.435 to 1202.015",
        "patrolPairId": None,
        "patrolPartnerId": None,
        "patrolPartnerName": None,
        "leaveBalance": {"lap": 25, "lhap": 15, "cl": 8, "rh": 2},
        "qrCodeId": "RD-EMP-100523",
        "remarks": "Senior Executive P-Way SMUN Section"
    },
    {
        "id": "EMP-100619",
        "employeeId": "EMP-100619",
        "awpoId": None,
        "name": "Shri Harpal Singh",
        "nameHi": "श्री हरपाल सिंह",
        "fatherName": "Shri Balwant Singh",
        "post": "Executive / P-Way",
        "designation": "Executive",
        "role": "OFFICER",
        "staffCategory": "PERMANENT",
        "dutyType": "OFFICER",
        "employmentType": "REGULAR",
        "email": "harpal.exec@dfcc.co.in",
        "phone": "7340855287",
        "emergencyContact": "7340855287",
        "headquarters": "IMSD SMUN",
        "assignedSection": "SBJN - CHAN Section",
        "joiningDate": "2022-01-15",
        "pmeDate": "2027-01-05",
        "leaveDate": "2026-11-10",
        "beatNo": "P-Way Section 2",
        "beatFromTo": "Km 1202.015 to 1249.720",
        "patrolPairId": None,
        "patrolPartnerId": None,
        "patrolPartnerName": None,
        "leaveBalance": {"lap": 22, "lhap": 15, "cl": 7, "rh": 2},
        "qrCodeId": "RD-EMP-100619",
        "remarks": "Executive P-Way In-Charge"
    },
    {
        "id": "EMP-100780",
        "employeeId": "EMP-100780",
        "awpoId": None,
        "name": "Shri Surendera Kumar",
        "nameHi": "श्री सुरेन्द्र कुमार",
        "fatherName": "Shri Ram Lal",
        "post": "MTS Regular (Multi-Tasking Staff)",
        "designation": "MTS",
        "role": "STAFF",
        "staffCategory": "PERMANENT",
        "dutyType": "MTS",
        "employmentType": "REGULAR",
        "email": "surendera.mts@dfcc.co.in",
        "phone": "7658008725",
        "emergencyContact": "7658008725",
        "headquarters": "IMSD SMUN",
        "assignedSection": "SMUN Yard & Depot",
        "joiningDate": "2022-07-20",
        "pmeDate": "2026-08-30",
        "leaveDate": "2026-09-01",
        "beatNo": "SMUN Yard",
        "beatFromTo": "Km 1170.435 to 1172.500",
        "patrolPairId": None,
        "patrolPartnerId": None,
        "patrolPartnerName": None,
        "leaveBalance": {"lap": 20, "lhap": 15, "cl": 6, "rh": 2},
        "qrCodeId": "RD-EMP-100780",
        "remarks": "Permanent MTS Staff SMUN Unit"
    }
]

staff_records.extend(perm_staff)

# 2. OUTSOURCE STAFF (9 records with Employee ID)
outsource_staff = [
    {
        "id": "EMP-88102",
        "employeeId": "EMP-88102",
        "awpoId": None,
        "name": "Shri Sanni Kumar Sharma",
        "nameHi": "श्री सन्नी कुमार शर्मा",
        "fatherName": "Shri Rajendra Sharma",
        "post": "Outsource MTS",
        "designation": "MTS",
        "role": "STAFF",
        "staffCategory": "OUTSOURCE",
        "dutyType": "MTS",
        "employmentType": "OUTSOURCED",
        "email": "sanni.sharma@dfcc.co.in",
        "phone": "7870056089",
        "emergencyContact": "7870056089",
        "headquarters": "IMSD SMUN Yard",
        "assignedSection": "SMUN Unit",
        "joiningDate": "2023-03-01",
        "pmeDate": "2026-10-15",
        "leaveDate": "2026-10-10",
        "beatNo": "Yard Area",
        "beatFromTo": "Km 1170.000 to 1172.000",
        "patrolPairId": None,
        "patrolPartnerId": None,
        "patrolPartnerName": None,
        "leaveBalance": {"lap": 15, "lhap": 10, "cl": 6, "rh": 2},
        "qrCodeId": "RD-EMP-88102",
        "remarks": "Outsource MTS Staff"
    },
    {
        "id": "EMP-88103",
        "employeeId": "EMP-88103",
        "awpoId": None,
        "name": "Shri Ranjeet Kumar",
        "nameHi": "श्री रणजीत कुमार",
        "fatherName": "Shri Ramesh Kumar",
        "post": "Computer Operator",
        "designation": "Jr.Executive",
        "role": "STAFF",
        "staffCategory": "OUTSOURCE",
        "dutyType": "OFFICE",
        "employmentType": "OUTSOURCED",
        "email": "ranjeet.it@dfcc.co.in",
        "phone": "9570703677",
        "emergencyContact": "9570703677",
        "headquarters": "IMSD SMUN Office",
        "assignedSection": "Admin & IT Office",
        "joiningDate": "2023-02-15",
        "pmeDate": "2027-02-15",
        "leaveDate": "2026-09-20",
        "beatNo": "Main Office",
        "beatFromTo": "Office HQ",
        "patrolPairId": None,
        "patrolPartnerId": None,
        "patrolPartnerName": None,
        "leaveBalance": {"lap": 15, "lhap": 10, "cl": 6, "rh": 2},
        "qrCodeId": "RD-EMP-88103",
        "remarks": "Computer Operator & IT Assistant"
    },
    {
        "id": "EMP-88104",
        "employeeId": "EMP-88104",
        "awpoId": None,
        "name": "Shri Gautam Kumar",
        "nameHi": "श्री गौतम कुमार",
        "fatherName": "Shri Ramchandra",
        "post": "Cleaner / Sweeper",
        "designation": "MTS",
        "role": "STAFF",
        "staffCategory": "OUTSOURCE",
        "dutyType": "OFFICE",
        "employmentType": "OUTSOURCED",
        "email": "gautam.clean@dfcc.co.in",
        "phone": "7011209332",
        "emergencyContact": "7011209332",
        "headquarters": "IMSD SMUN Depot",
        "assignedSection": "Depot & Office Premise",
        "joiningDate": "2023-04-10",
        "pmeDate": "2026-12-01",
        "leaveDate": "2026-10-05",
        "beatNo": "HQ Area",
        "beatFromTo": "SMUN Complex",
        "patrolPairId": None,
        "patrolPartnerId": None,
        "patrolPartnerName": None,
        "leaveBalance": {"lap": 15, "lhap": 10, "cl": 6, "rh": 2},
        "qrCodeId": "RD-EMP-88104",
        "remarks": "Facility & Sanitation Staff"
    },
    {
        "id": "EMP-88105",
        "employeeId": "EMP-88105",
        "awpoId": None,
        "name": "Shri Lal Chand",
        "nameHi": "श्री लाल चंद",
        "fatherName": "Shri Munshi Ram",
        "post": "Pump Operator",
        "designation": "MTS",
        "role": "STAFF",
        "staffCategory": "OUTSOURCE",
        "dutyType": "OFFICE",
        "employmentType": "OUTSOURCED",
        "email": "lalchand.pump@dfcc.co.in",
        "phone": "9649218216",
        "emergencyContact": "9649218216",
        "headquarters": "IMSD SMUN Pump House",
        "assignedSection": "Water Supply & Pumping",
        "joiningDate": "2023-01-20",
        "pmeDate": "2026-11-15",
        "leaveDate": "2026-09-12",
        "beatNo": "Pump Station",
        "beatFromTo": "SMUN Water Works",
        "patrolPairId": None,
        "patrolPartnerId": None,
        "patrolPartnerName": None,
        "leaveBalance": {"lap": 15, "lhap": 10, "cl": 6, "rh": 2},
        "qrCodeId": "RD-EMP-88105",
        "remarks": "Pump Operator IMSD SMUN"
    },
    {
        "id": "EMP-88106",
        "employeeId": "EMP-88106",
        "awpoId": None,
        "name": "Shri Sudhir Kumar",
        "nameHi": "श्री सुधीर कुमार",
        "fatherName": "Shri Naresh Kumar",
        "post": "Office Boy",
        "designation": "MTS",
        "role": "STAFF",
        "staffCategory": "OUTSOURCE",
        "dutyType": "OFFICE",
        "employmentType": "OUTSOURCED",
        "email": "sudhir.office@dfcc.co.in",
        "phone": "8210018687",
        "emergencyContact": "8210018687",
        "headquarters": "IMSD SMUN Office",
        "assignedSection": "Office Dispatch & Records",
        "joiningDate": "2023-05-15",
        "pmeDate": "2027-05-15",
        "leaveDate": "2026-08-30",
        "beatNo": "Admin Section",
        "beatFromTo": "SMUN Building",
        "patrolPairId": None,
        "patrolPartnerId": None,
        "patrolPartnerName": None,
        "leaveBalance": {"lap": 15, "lhap": 10, "cl": 6, "rh": 2},
        "qrCodeId": "RD-EMP-88106",
        "remarks": "Office Assistance & Messenger"
    },
    {
        "id": "EMP-88107",
        "employeeId": "EMP-88107",
        "awpoId": None,
        "name": "Shri Suraj Verma",
        "nameHi": "श्री सूरज वर्मा",
        "fatherName": "Shri Ram Avtar",
        "post": "Gardener",
        "designation": "MTS",
        "role": "STAFF",
        "staffCategory": "OUTSOURCE",
        "dutyType": "OFFICE",
        "employmentType": "OUTSOURCED",
        "email": "suraj.garden@dfcc.co.in",
        "phone": "9239845014",
        "emergencyContact": "9239845014",
        "headquarters": "IMSD SMUN Campus",
        "assignedSection": "Campus Horticulture",
        "joiningDate": "2023-06-01",
        "pmeDate": "2026-09-25",
        "leaveDate": "2026-09-10",
        "beatNo": "Campus Grounds",
        "beatFromTo": "SMUN Green Belt",
        "patrolPairId": None,
        "patrolPartnerId": None,
        "patrolPartnerName": None,
        "leaveBalance": {"lap": 15, "lhap": 10, "cl": 6, "rh": 2},
        "qrCodeId": "RD-EMP-88107",
        "remarks": "Horticulture Maintenance"
    },
    {
        "id": "EMP-88108",
        "employeeId": "EMP-88108",
        "awpoId": None,
        "name": "Shri Amar Molana",
        "nameHi": "श्री अमर मौलाना",
        "fatherName": "Shri Jagdish Molana",
        "post": "Track Supervisor",
        "designation": "Jr.Executive",
        "role": "STAFF",
        "staffCategory": "OUTSOURCE",
        "dutyType": "GANG",
        "employmentType": "OUTSOURCED",
        "email": "amar.molana@dfcc.co.in",
        "phone": "7788020121",
        "emergencyContact": "7788020121",
        "headquarters": "IMSD SMUN Gang 01",
        "assignedSection": "KRJN - SBJN Gang Beat",
        "joiningDate": "2022-11-01",
        "pmeDate": "2026-11-01",
        "leaveDate": "2026-09-05",
        "beatNo": "Gang 01",
        "beatFromTo": "Km 1167.210 to 1188.575",
        "patrolPairId": None,
        "patrolPartnerId": None,
        "patrolPartnerName": None,
        "leaveBalance": {"lap": 15, "lhap": 10, "cl": 6, "rh": 2},
        "qrCodeId": "RD-EMP-88108",
        "remarks": "Outsource Track Gang Supervisor"
    },
    {
        "id": "EMP-88109",
        "employeeId": "EMP-88109",
        "awpoId": None,
        "name": "Shri Arjun Kumar",
        "nameHi": "श्री अर्जुन कुमार",
        "fatherName": "Shri Ratan Singh",
        "post": "Track Mate",
        "designation": "MTS",
        "role": "STAFF",
        "staffCategory": "OUTSOURCE",
        "dutyType": "GANG",
        "employmentType": "OUTSOURCED",
        "email": "arjun.mate@dfcc.co.in",
        "phone": "8295416161",
        "emergencyContact": "8295416161",
        "headquarters": "IMSD SMUN Gang 02",
        "assignedSection": "SBJN - Sirhind Gang Beat",
        "joiningDate": "2023-01-10",
        "pmeDate": "2027-01-10",
        "leaveDate": "2026-10-12",
        "beatNo": "Gang 02",
        "beatFromTo": "Km 1188.575 to 1220.000",
        "patrolPairId": None,
        "patrolPartnerId": None,
        "patrolPartnerName": None,
        "leaveBalance": {"lap": 15, "lhap": 10, "cl": 6, "rh": 2},
        "qrCodeId": "RD-EMP-88109",
        "remarks": "Track Mate Field Crew"
    },
    {
        "id": "EMP-88110",
        "employeeId": "EMP-88110",
        "awpoId": None,
        "name": "Shri Gaya Prashad",
        "nameHi": "श्री गया प्रसाद",
        "fatherName": "Shri Shiv Prasad",
        "post": "Track Gangman",
        "designation": "MTS",
        "role": "STAFF",
        "staffCategory": "OUTSOURCE",
        "dutyType": "GANG",
        "employmentType": "OUTSOURCED",
        "email": "gaya.gang@dfcc.co.in",
        "phone": "8295416161",
        "emergencyContact": "8295416161",
        "headquarters": "IMSD SMUN Gang 03",
        "assignedSection": "Sirhind - Chawapail Beat",
        "joiningDate": "2023-02-20",
        "pmeDate": "2026-10-20",
        "leaveDate": "2026-09-18",
        "beatNo": "Gang 03",
        "beatFromTo": "Km 1220.000 to 1249.720",
        "patrolPairId": None,
        "patrolPartnerId": None,
        "patrolPartnerName": None,
        "leaveBalance": {"lap": 15, "lhap": 10, "cl": 6, "rh": 2},
        "qrCodeId": "RD-EMP-88110",
        "remarks": "Track Maintenance Gangman"
    }
]

staff_records.extend(outsource_staff)

# 3. EX-SERVICE MAN (From Google Sheet: Keymen 18, Watchmen 3, Patrolmen 29, Gatemen 18)
patrol_pair_map = {
    22: {"pairId": "SPN-02", "partnerSr": 23, "shift": "NIGHT"},
    23: {"pairId": "SPN-02", "partnerSr": 22, "shift": "NIGHT"},
    24: {"pairId": "SPN-12", "partnerSr": 25, "shift": "NIGHT"},
    25: {"pairId": "SPN-12", "partnerSr": 24, "shift": "NIGHT"},
    26: {"pairId": "SPN-03", "partnerSr": 27, "shift": "NIGHT"},
    27: {"pairId": "SPN-03", "partnerSr": 26, "shift": "NIGHT"},
    28: {"pairId": "SPN-04", "partnerSr": 29, "shift": "NIGHT"},
    29: {"pairId": "SPN-04", "partnerSr": 28, "shift": "NIGHT"},
    30: {"pairId": "SPN-06", "partnerSr": 31, "shift": "NIGHT"},
    31: {"pairId": "SPN-06", "partnerSr": 30, "shift": "NIGHT"},
    32: {"pairId": "SPN-07", "partnerSr": 33, "shift": "NIGHT"},
    33: {"pairId": "SPN-07", "partnerSr": 32, "shift": "NIGHT"},
    34: {"pairId": "SPN-08", "partnerSr": 35, "shift": "NIGHT"},
    35: {"pairId": "SPN-08", "partnerSr": 34, "shift": "NIGHT"},
    36: {"pairId": "SPN-09", "partnerSr": 37, "shift": "NIGHT"},
    37: {"pairId": "SPN-09", "partnerSr": 36, "shift": "NIGHT"},
    38: {"pairId": "SPN-10", "partnerSr": 39, "shift": "NIGHT"},
    39: {"pairId": "SPN-10", "partnerSr": 38, "shift": "NIGHT"},
    40: {"pairId": "SPN-11", "partnerSr": 41, "shift": "NIGHT"},
    41: {"pairId": "SPN-11", "partnerSr": 40, "shift": "NIGHT"},
}

ex_rows = []
for r in rows[2:]:
    if not r or len(r) < 8 or not r[0].strip().isdigit():
        continue
    sr = int(r[0].strip())
    awpo = r[1].strip()
    name = r[2].strip()
    father = r[3].strip()
    beat = r[4].strip()
    km = r[5].strip()
    mobile = r[6].strip().replace(' ', '').replace('-', '')
    desig = r[7].strip()
    residence = r[8].strip() if len(r) > 8 else ''
    district = r[9].strip() if len(r) > 9 else ''
    other_contact = r[10].strip() if len(r) > 10 else ''

    awpo_formatted = f"AWPO-{awpo}" if awpo else f"AWPO-{70000+sr}"

    duty_type = "KEYMAN"
    if "watchman" in desig.lower() or 19 <= sr <= 21:
        duty_type = "WATCHMAN"
    elif "patrolman" in desig.lower() or 22 <= sr <= 50:
        duty_type = "PATROLMAN"
    elif "gate" in desig.lower() or 51 <= sr <= 68:
        duty_type = "GATEMAN"

    ex_rows.append({
        "sr": sr,
        "awpoId": awpo_formatted,
        "name": f"Shri {name}" if not name.startswith("Shri") else name,
        "fatherName": f"Shri {father}" if father and not father.startswith("Shri") else (father or "Shri Ex-Serviceman"),
        "post": desig,
        "designation": "MTS",
        "role": "STAFF",
        "staffCategory": "EX_SERVICEMAN",
        "dutyType": duty_type,
        "employmentType": "OUTSOURCED",
        "email": f"{awpo_formatted.lower()}@dfcc.co.in",
        "phone": mobile if mobile else "8872671873",
        "emergencyContact": other_contact if other_contact else (mobile or "8872671873"),
        "headquarters": f"{residence}, {district}" if residence else "IMSD SMUN Sector",
        "assignedSection": f"IMSD SMUN {beat}",
        "joiningDate": "2023-04-01",
        "pmeDate": "2026-10-15",
        "leaveDate": "2026-09-01",
        "beatNo": beat,
        "beatFromTo": km,
        "leaveBalance": {"lap": 15, "lhap": 10, "cl": 6, "rh": 2},
        "qrCodeId": f"RD-{awpo_formatted}",
        "remarks": f"Ex-Serviceman {duty_type} • Beat: {beat} ({km})"
    })

ex_dict = {r["sr"]: r for r in ex_rows}
for sr, r in ex_dict.items():
    if sr in patrol_pair_map:
        info = patrol_pair_map[sr]
        partner = ex_dict.get(info["partnerSr"])
        r["patrolPairId"] = info["pairId"]
        r["patrolPartnerId"] = partner["awpoId"] if partner else None
        r["patrolPartnerName"] = partner["name"] if partner else None
    elif r["dutyType"] == "PATROLMAN":
        r["patrolPairId"] = r["beatNo"]
        r["patrolPartnerId"] = None
        r["patrolPartnerName"] = None

for r in ex_rows:
    staff_record = {
        "id": r["awpoId"],
        "employeeId": None,
        "awpoId": r["awpoId"],
        "name": r["name"],
        "nameHi": "",
        "fatherName": r["fatherName"],
        "post": r["post"],
        "designation": "MTS",
        "role": "STAFF",
        "staffCategory": "EX_SERVICEMAN",
        "dutyType": r["dutyType"],
        "employmentType": "OUTSOURCED",
        "email": r["email"],
        "phone": r["phone"],
        "emergencyContact": r["emergencyContact"],
        "headquarters": r["headquarters"],
        "assignedSection": r["assignedSection"],
        "joiningDate": r["joiningDate"],
        "pmeDate": r["pmeDate"],
        "leaveDate": r["leaveDate"],
        "beatNo": r["beatNo"],
        "beatFromTo": r["beatFromTo"],
        "patrolPairId": r.get("patrolPairId"),
        "patrolPartnerId": r.get("patrolPartnerId"),
        "patrolPartnerName": r.get("patrolPartnerName"),
        "leaveBalance": r["leaveBalance"],
        "qrCodeId": r["qrCodeId"],
        "remarks": r["remarks"]
    }
    staff_records.append(staff_record)

print(f"Total Staff Records Generated: {len(staff_records)}")
print(f"  Permanent: {len([s for s in staff_records if s['staffCategory'] == 'PERMANENT'])}")
print(f"  Outsource: {len([s for s in staff_records if s['staffCategory'] == 'OUTSOURCE'])}")
print(f"  Ex-Service: {len([s for s in staff_records if s['staffCategory'] == 'EX_SERVICEMAN'])}")

with open('staff_master_seed.json', 'w') as f:
    json.dump(staff_records, f, indent=2)
